
// Objective-C API for talking to the following Go packages
//
//	mgitiosbridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MGitBridge_FRAMEWORK_H__
#define __MGitBridge_FRAMEWORK_H__

#include "Mgitiosbridge.objc.h"
#include "Universe.objc.h"

#endif
