// Objective-C API for talking to mgitiosbridge Go package.
//   gobind -lang=objc mgitiosbridge
//
// File is generated by gobind. Do not edit.

#ifndef __Mgitiosbridge_H__
#define __Mgitiosbridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Help returns MGit help information for iOS
This function provides the same help text as the main MGit project
 */
FOUNDATION_EXPORT NSString* _Nonnull MgitiosbridgeHelp(void);

/**
 * SimpleAdd performs a simple addition (for basic functionality testing)
 */
FOUNDATION_EXPORT long MgitiosbridgeSimpleAdd(long a, long b);

/**
 * TestLogging performs comprehensive logging tests for iOS debugging
 */
FOUNDATION_EXPORT NSString* _Nonnull MgitiosbridgeTestLogging(void);

#endif
